name: Question
description: Ask about something here.
labels: ["question", "status: pending triage"]
body:
  - type: textarea
    attributes:
      label: What is your question?
    validations:
      required: true

  - type: textarea
    id: buildVersion
    attributes:
      label: "What version did the bug occur?"
      description: "You HAVE to answer this. If you don't know what version, please go to the main menu and look at the bottem-left of the window."
    validations:
      required: true

  - type: dropdown
    id: currentBuildCheck
    attributes:
      label: "Did you check if the problem occurs in the latest build?"
      description: "You don't need to answer this if this is happening on the latest version."
      options:
        - "No"
        - "Yes"
    validations:
      required: false

  - type: dropdown
    id: commitBuildCheck
    attributes:
      label: "Commit build or Release build?"
      options:
        - "Release build"
        - "Commit Build of latest version."
        - "Older commit build of the latest version."
    validations:
      required: true

  - type: dropdown
    id: knownIssueCheck
    attributes:
      label: "Did you check if the problem is in the pinned issue?"
      description: "[Click me here to check if there is.](https://github.com/JordanSantiagoYT/FNF-JS-Engine/issues/1031)"
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: dropdown
    id: dupeCheck
    attributes:
      label: "Did you check if there's any similar issues?"
      description: "Go to the search bar on the issues tab and see if there is."
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: textarea
    id: cmdLogs
    attributes:
      label: "Command Prompt/Terminal logs/Crash logs (if existing)"
    validations:
      required: false
